"""Reproduce the simulator throughput numbers locally.

The reference figures in docs/02-mechanics-deltas.md were measured in a cloud
container. Local numbers will differ and the local ones are what matter, since
they are what the M8 engine decision gets made against.

Usage: python scripts/bench.py [--out docs/benchmarks.md]
"""

from __future__ import annotations

import argparse
import platform
import random
import time
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from champions.search.oracle import SimServer
from champions.teams import ALPHA, BETA, load_team

FORMAT_ID = "gen9championsvgc2026regmb"
REPO_ROOT = Path(__file__).resolve().parent.parent
SHOWDOWN_COMMIT_FILE = REPO_ROOT / "vendor" / "SHOWDOWN_COMMIT"

# Single core, Node 22, from docs/02-mechanics-deltas.md section 5.
REFERENCE = {
    "battles_per_s": 26.8,
    "turns_per_s": 303.0,
    "serializations_per_s": 2386.0,
    "deserializations_per_s": 1026.0,
}


@dataclass
class Measurement:
    name: str
    per_second: float
    ms_each: float
    samples: int


def _bench(name: str, operation: Callable[[], object], samples: int) -> Measurement:
    start = time.perf_counter()
    for _ in range(samples):
        operation()
    elapsed = time.perf_counter() - start
    return Measurement(
        name=name,
        per_second=samples / elapsed,
        ms_each=(elapsed / samples) * 1000,
        samples=samples,
    )


def _play_one_battle(server: SimServer, rng: random.Random) -> int:
    """Play a battle to completion with random legal choices. Returns turns."""
    state = server.create(
        FORMAT_ID,
        load_team(ALPHA),
        load_team(BETA),
        seed=[rng.randrange(0x10000) for _ in range(4)],
    )
    handle = state["handle"]

    state = server.step(handle, "team 1234", "team 1234")
    # `default` asks Showdown for the first legal choice, which keeps the
    # benchmark measuring simulator throughput rather than our action
    # enumeration. Turn count is what is being timed here.
    while not state["ended"] and state["turn"] < 200:
        state = server.step(handle, "default", "default")

    turns = state["turn"]
    server.destroy(handle)
    return turns


def run_benchmark(n_battles: int = 20, n_ops: int = 300) -> list[Measurement]:
    rng = random.Random(0)
    results: list[Measurement] = []

    with SimServer() as server:
        # Full battles played to completion.
        turn_counts: list[int] = []
        start = time.perf_counter()
        for _ in range(n_battles):
            turn_counts.append(_play_one_battle(server, rng))
        elapsed = time.perf_counter() - start

        results.append(
            Measurement(
                "full battles", n_battles / elapsed, (elapsed / n_battles) * 1000, n_battles
            )
        )
        total_turns = sum(turn_counts)
        results.append(
            Measurement(
                "turns advanced", total_turns / elapsed, (elapsed / total_turns) * 1000, total_turns
            )
        )

        # Serialize / deserialize / clone, measured on a mid-battle position.
        state = server.create(FORMAT_ID, load_team(ALPHA), load_team(BETA), seed=[1, 2, 3, 4])
        handle = state["handle"]
        server.step(handle, "team 1234", "team 1234")
        for _ in range(3):
            server.step(handle, "default", "default")

        serialized = server.serialize(handle)
        results.append(_bench("serializations", lambda: server.serialize(handle), n_ops))
        results.append(_bench("deserializations", lambda: server.deserialize(serialized), n_ops))
        results.append(_bench("clone + step", lambda: _clone_and_step(server, handle), n_ops // 3))

    return results


def _clone_and_step(server: SimServer, handle: int) -> None:
    cloned = server.clone(handle)["handle"]
    server.step(cloned, "default", "default")
    server.destroy(cloned)


def format_report(results: list[Measurement]) -> str:
    commit = (
        SHOWDOWN_COMMIT_FILE.read_text(encoding="utf-8").strip()
        if SHOWDOWN_COMMIT_FILE.exists()
        else "unknown"
    )
    by_name = {m.name: m for m in results}

    lines = [
        "# Simulator Benchmark",
        "",
        f"Generated by `scripts/bench.py` on {datetime.now(UTC):%Y-%m-%d}, against "
        f"`vendor/showdown` at `{commit}`.",
        "",
        f"Machine: {platform.platform()}, {platform.processor() or 'unknown cpu'}.",
        "Single process, single core, over JSON-RPC on stdio, so these figures "
        "include the Python/Node round trip that any real caller also pays.",
        "",
        "## Local measurements",
        "",
        "| Operation | Rate | Cost | Samples |",
        "| --- | --- | --- | --- |",
    ]
    for m in results:
        lines.append(
            f"| {m.name} | {m.per_second:,.1f} per second | {m.ms_each:.2f} ms | {m.samples} |"
        )

    lines += [
        "",
        "## Against the reference",
        "",
        "Reference figures are from a cloud container (docs/02-mechanics-deltas.md "
        "section 5), measured in-process rather than over JSON-RPC. The local "
        "numbers are the ones the M8 engine decision is made against.",
        "",
        "| Operation | Reference | Local | Ratio |",
        "| --- | --- | --- | --- |",
    ]
    comparisons = [
        ("full battles", "battles_per_s"),
        ("turns advanced", "turns_per_s"),
        ("serializations", "serializations_per_s"),
        ("deserializations", "deserializations_per_s"),
    ]
    for local_name, ref_key in comparisons:
        local = by_name.get(local_name)
        if local is None:
            continue
        reference = REFERENCE[ref_key]
        lines.append(
            f"| {local_name} | {reference:,.1f}/s | {local.per_second:,.1f}/s | "
            f"{local.per_second / reference:.2f}x |"
        )

    clone_step = by_name.get("clone + step")
    if clone_step:
        lines += [
            "",
            f"One clone plus one step costs {clone_step.ms_each:.2f} ms locally, against "
            "roughly 4.7 ms for the reference container.",
        ]

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="docs/benchmarks.md")
    parser.add_argument("--battles", type=int, default=20)
    parser.add_argument("--ops", type=int, default=300)
    args = parser.parse_args()

    results = run_benchmark(n_battles=args.battles, n_ops=args.ops)
    report = format_report(results)

    out_path = REPO_ROOT / args.out
    out_path.write_text(report, encoding="utf-8")
    print(report)
    print(f"written to {args.out}")


if __name__ == "__main__":
    main()
